{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: sap-integration
  labels:
    app.kubernetes.io/name: sap-integration-platform
    app.kubernetes.io/managed-by: Helm
{{- end }}
