{{- range $name, $service := .Values.services }}
{{- if and $service.enabled $service.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.componentFullname" (dict "root" $ "service" $service) }}
  namespace: {{ include "platform.namespace" $ }}
  labels:
{{ include "platform.labels" (dict "root" $ "service" $service) | nindent 4 }}
  {{- with $service.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.service.type }}
  selector:
{{ include "platform.selectorLabels" (dict "root" $ "service" $service) | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
{{- end }}
